const EXPECTED_SUPPORTED_PHYLOPLOT_ATTRIBUTES = (
    :clip_planes,
    :useedgelength,
    :showtiplabel,
    :shownodelabel,
    :shownodenumber,
    :showedgelength,
    :showedgenumber,
    :showgamma,
    :edgecolor,
    :defaultedgecolor,
    :majorhybridedgecolor,
    :minorhybridedgecolor,
    :edgewidth,
    :minorlinetype,
    :arrowlen,
    :nodelabel,
    :edgelabel,
    :nodeimages,
    :edgeimages,
    # :nodecex,
    # :edgecex,
    :nodefontsize,
    :edgefontsize,
    :nodelabelcolor,
    :edgelabelcolor,
    :edgenumbercolor,
    :nodelabeladj,
    :edgelabeladj,
    :tipoffset,
    # :tipcex,
    :tipfontsize,
    :xlim,
    :ylim,
    :style,
)
