[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PhyloMakie = "ccbd7354-87c9-452d-961c-17247803ee9f"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
PhyloPicMakie = "29f7fcc2-58b8-448e-949b-ed9dd2d8a249"

[sources]
PhyloMakie = {path = ".."}
PhyloPicMakie = {url = "https://github.com/jeetsukumaran/PhyloPicMakie.jl.git", rev = "main"}
