const VERIFICATION_FOUNDATION = (
    target_public_surfaces = (
        (
            id = :phyloplot,
            public_name = "phyloplot",
            implemented = true,
            direct_proof_deferred = false,
            direct_proof_owner = 5,
            docs_visibility = :documented_convenience_surface,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "Makie.FigureAxisPlot",
        ),
        (
            id = :phyloplot_bang,
            public_name = "phyloplot!",
            implemented = true,
            direct_proof_deferred = false,
            direct_proof_owner = 5,
            docs_visibility = :documented_convenience_surface,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "PhyloPlot on an existing Makie axis-like owner",
        ),
        (
            id = :plot_net,
            public_name = "plot(net)",
            implemented = true,
            direct_proof_deferred = false,
            direct_proof_owner = 5,
            docs_visibility = :documented_primary_surface,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "Makie.FigureAxisPlot via Makie dispatch",
        ),
        (
            id = :plot_bang_axis_net,
            public_name = "plot!(ax, net)",
            implemented = true,
            direct_proof_deferred = false,
            direct_proof_owner = 5,
            docs_visibility = :documented_primary_surface,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "PhyloPlot on an existing Makie axis-like owner via Makie dispatch",
        ),
    ),
    lock_items = (
        (number = 1, title = "Makie-native public plot owner"),
        (number = 2, title = "Makie-native public attribute surface"),
        (number = 3, title = "Compatibility-first owner demotion"),
        (number = 4, title = "Layout/render owner reuse"),
        (number = 5, title = "Public mutation/composability boundary"),
        (number = 6, title = "Multi-surface direct public proof"),
        (number = 7, title = "Honest verification/docs truth surface"),
    ),
    public_attribute_owner = (
        source_files = ("src/public_attribute_model.jl",),
        canonical_payload = "PhyloPlotAttributes",
        supported_public_attributes = SUPPORTED_PHYLOPLOT_ATTRIBUTES,
        recipe_attribute_surface = "Makie.attribute_names(PhyloPlot)",
        omitted_control_note = "The tranche-5 public surface intentionally omits separate controls for internal-node-name color, internal-node-name size, edge-length-label size, gamma-label size, and node-number size; the existing render-owner defaults remain authoritative for those groupings.",
        bridge_target = "bridge_phylo_plot_attributes(attributes; x_limits, y_limits)::PlotKeywordSpec",
        legacy_rejection = (
            source = "Makie.deprecated_attributes(::Type{<:PhyloPlot})",
            rejected_spellings = Tuple(migration.legacy for migration in PHYLOPLOT_ATTRIBUTE_MIGRATIONS),
        ),
        reviewer_gate = (
            clear = "the public snake_case surface is exactly the tranche-5 attribute set, style-dependent minor-edge defaults remain source-backed, DataFrame inputs are copied on entry, legacy public spellings are rejected at the recipe boundary, and PlotKeywordSpec survives only as the local bridge target.",
            reject = "it lets legacy names or preorder back onto the public surface, re-centers compatibility structs as the public semantic owner, or reintroduces omitted styling controls as ad hoc new public knobs.",
        ),
    ),
    compatibility_keyword_bridge = (
        source_files = (
            "src/public_attribute_model.jl",
            "src/keyword_normalization.jl",
            "src/keyword_contract.jl",
        ),
        public_semantic_center = false,
        canonical_bridge = "bridge_phylo_plot_attributes(attributes; x_limits, y_limits)::PlotKeywordSpec",
        retained_internal_payload = "PlotKeywordSpec",
        retained_for = (
            "prepare_plot_layout(net, spec)::PlotLayout",
            "render_plot!(target, net, spec, layout)::PlotRenderLayers",
        ),
        internal_preorder_policy = "The bridge always sets preorder=true and only runs on a deepcopy-owned HybridNetwork inside the public plot owner.",
        reviewer_gate = (
            clear = "the compatibility layer is a tightly local bridge from the tranche-5 public attribute payload into PlotKeywordSpec, and it no longer owns public naming, public limits, or caller-owned network semantics.",
            reject = "it remains the public semantic center, accepts the legacy public keyword surface directly, or owns caller-visible mutation and limit-validation policy.",
        ),
    ),
    layout_annotation_owner = (
        source_files = (
            "src/layout_engine.jl",
            "src/annotation_data.jl",
        ),
        supporting_types = (
            "PlotGeometry",
            "PlotBounds",
            "PlotAnnotationData",
        ),
        canonical_payload = "PlotLayout",
        regression_suites = (
            "test/test_layout_engine.jl",
            "test/test_annotation_data.jl",
        ),
        closed_helper_regressions = (
            :edgenode_coords_with_lengths_fulltree,
            :edgenode_coords_with_lengths_majortree,
            :edgenode_coords_without_lengths_majortree,
            :level2_network_with_gamma,
            :level2_network_without_gamma,
            :mixed_missing_lengths_warning,
            :all_missing_lengths_fulltree_fallback,
            :incompatible_root,
            :preorder_mutation_boundary,
            :nodelabel_validation_and_prep,
            :edgelabel_validation_and_prep,
            :major_tree_minor_edge_midpoint,
            :helper_bounds_messages,
        ),
        render_consumer = (
            owner_tranche = 4,
            owner = "render_plot!(target, net, spec, layout)::PlotRenderLayers",
            source_file = "src/render_adapter.jl",
            contracts = (
                "Render-time proof consumes PlotLayout geometry, bounds, and annotation tables without local geometry recomputation.",
                "Render-time proof applies only the final x and y limits carried by the bridged PlotKeywordSpec.",
            ),
        ),
        public_surface_consumer = (
            owner_tranche = 5,
            owner = "Makie.plot!(plot::PhyloPlot)",
            source_file = "src/public_plot_owner.jl",
            contracts = (
                "The public plot owner computes PlotLayout once on a deepcopy-owned HybridNetwork and passes that payload directly to render_plot!.",
                "Public x_limits and y_limits validation reuses the helper-owned PlotBounds messages only after helper bounds are known.",
            ),
        ),
        reviewer_gate = (
            clear = "src/layout_engine.jl and src/annotation_data.jl remain the only helper owners, PlotLayout remains the canonical helper payload, render_plot! consumes that payload directly, and the tranche-5 public plot owner adds no duplicate helper math.",
            reject = "it reimplements geometry, midpoint, or bounds-message semantics in the public plot owner, leaves PlotLayout implicit, or pushes helper ownership back into render-facing code.",
        ),
    ),
    render_owner = (
        source_files = ("src/render_adapter.jl",),
        supporting_types = (
            "SegmentRenderLayer",
            "ArrowTipRenderLayer",
            "TextRenderLayer",
            "PlotRenderLayers",
        ),
        typed_layer_bundle = "PlotRenderLayers",
        regression_suites = (
            "test/support/render_test_helpers.jl",
            "test/test_render_adapter.jl",
        ),
        source_set_note = ".workflow-docs/202605090307_phylomakie-makie-rebuild/04-01_tranche-04--makie-source-set.md",
        makie_source_files = (
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/recipes.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/figureplotting.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/Makie.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_plots.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_recipes/arrows.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_recipes/text.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/display.jl",
            "/home/jeetsukumaran/.julia/packages/CairoMakie/hql6v/src/screen.jl",
        ),
        primitive_entrypoints = (
            "linesegments!",
            "arrows2d!",
            "text!",
            "Makie.colorbuffer",
        ),
        public_owner_reuse = (
            owner_tranche = 5,
            owner = "Makie.plot!(plot::PhyloPlot)",
            contract = "The public recipe owner reuses render_plot! directly for both Axis and Plot targets without duplicating primitive render logic.",
        ),
        closed_render_regressions = (
            :style_distinction_fulltree_vs_majortree,
            :minorlinetype_numeric_dotted_rendering,
            :minorlinetype_blank_hides_minor_edges,
            :edgecolor_dict_fallback,
            :gamma_color_policy,
            :text_cex_scope_policy,
            :vector_text_cex_rendering,
            :tip_label_rendering,
            :internal_node_name_rendering,
            :node_number_rendering,
            :node_label_rendering,
            :edge_label_rendering,
            :edge_length_rendering,
            :edge_number_rendering,
            :explicit_limit_application,
        ),
        reviewer_gate = (
            clear = "render_plot! is the only internal render owner, PlotRenderLayers exposes the typed render proof surface, linesegments!, arrows2d!, text!, and Makie.colorbuffer remain the ratified primitive path, and the tranche-5 public recipe owner reuses the same owner directly.",
            reject = "it adds a second render owner, reintroduces hidden current-axis state, lets public-surface proof fork the primitive path, or lets proof collapse to docs-only or source-text checks.",
        ),
    ),
    public_plot_owner = (
        source_files = ("src/public_plot_owner.jl",),
        public_recipe = "Makie.@recipe PhyloPlot (net,) begin ... end",
        makie_dispatch = (
            "Makie.plottype(::PhyloNetworks.HybridNetwork) = PhyloPlot",
            "Makie.plot!(plot::PhyloPlot)",
        ),
        supported_surfaces = (
            "plot(net)",
            "plot!(ax, net)",
            "phyloplot",
            "phyloplot!",
        ),
        stored_artifacts = (
            "resolved_layout",
            "render_layers",
            "data_limits",
        ),
        direct_proof_suites = (
            "test/test_PhyloMakie.jl",
            "test/test_public_attribute_model.jl",
            "test/test_public_plot_owner.jl",
        ),
        docs_surface = (
            "docs/src/index.md",
            "docs/src/public-api.md",
            "docs/src/verification-foundation.md",
        ),
        caller_owned_network_boundary = "deepcopy(Makie.to_value(plot[:net]))",
        reviewer_gate = (
            clear = "a single Makie recipe owner drives plot(net), plot!(ax, net), phyloplot, and phyloplot!; the owner stores resolved_layout, render_layers, and data_limits on the returned plot; and caller-owned HybridNetwork inputs remain unchanged.",
            reject = "it forks surface semantics between plot and phyloplot, mutates the caller-owned network implicitly, or adds wrapper-owned render or layout logic outside the single Makie recipe owner.",
        ),
    ),
    accepted_design_scenarios = (
        simple_tree_no_hybrid = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Renders without error; no hybrid-edge drawing code is invoked.",
        ),
        single_reticulation_gamma = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Major and minor hybrid edges are visible in distinct colors, and the minor edge has an arrow tip.",
        ),
        style_distinction_fulltree_vs_majortree = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "The full-tree style and major-tree style remain visually distinct.",
        ),
        useedgelength_scaling = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Node x positions follow edge lengths, and missing lengths render as 1.0.",
        ),
        dataframe_label_rendering = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Node and edge labels render at the correct midpoint anchors after validation.",
        ),
        showgamma_rendering = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Hybrid-edge gamma text renders with the correct major and minor color semantics.",
        ),
        edgecolor_dict_fallback = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Mapped edges use the provided colors and unmapped edges fall back to the default edge color.",
        ),
        composable_dual_axes = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 5,
            closure_status = :closed_public_surface_proof,
            required_output = "Two networks render into separate axes without coordinate bleed-through.",
        ),
    ),
    upstream_helper_regressions = (
        edgenode_coords_with_lengths_fulltree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        edgenode_coords_with_lengths_majortree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        edgenode_coords_without_lengths_majortree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        nodelabel_validation_and_prep = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.check_nodedataframe / prepare_nodedataframe",
        ),
        edgelabel_validation_and_prep = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.prepare_edgedataframe",
        ),
        level2_network_with_gamma = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        level2_network_without_gamma = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
    ),
    green_state_gates = (
        (
            id = :root_makie_activation,
            artifact = "The repo-local root environment loads Makie from a repo-owned dependency declaration.",
            command = "julia --project=. -e 'using Makie'",
        ),
        (
            id = :test_makie_activation,
            artifact = "The repo-local test environment loads CairoMakie and Makie for render verification.",
            command = "julia --project=test -e 'using CairoMakie; using Makie'",
        ),
        (
            id = :docs_makie_activation,
            artifact = "The repo-local docs environment loads CairoMakie and Makie for render docs.",
            command = "julia --project=docs -e 'using CairoMakie; using Makie'",
        ),
        (
            id = :package_tests,
            artifact = "Shell-owner, compatibility-owner, public-attribute-owner, helper-owner, render-owner, public-plot-owner, and verification-owner tests pass together under the repo-local test project.",
            command = "julia --project=test test/runtests.jl",
        ),
        (
            id = :aqua,
            artifact = "Aqua remains supplemental proof inside the test suite and accepts the package-side Makie dependency as live.",
            command = "Aqua.test_all(PhyloMakie)",
        ),
        (
            id = :jet,
            artifact = "JET remains supplemental proof inside the test suite.",
            command = "JET.test_package(PhyloMakie; target_modules = (PhyloMakie,))",
        ),
        (
            id = :docs_build,
            artifact = "Documenter renders the source-backed public-api, verification-foundation, and render-verification pages from live CairoMakie code.",
            command = "julia --project=docs docs/make.jl",
        ),
    ),
    current_status = (
        (
            id = :dependency_activation_closed,
            status = :closed_in_tranche_4,
            fact = "On 2026-05-10, the root, test, and docs projects all resolved and loaded the Makie-family dependencies through repo-owned environments.",
        ),
        (
            id = :render_owner_closed,
            status = :closed_in_tranche_4,
            fact = "On 2026-05-10, src/render_adapter.jl landed render_plot!(target, net, spec, layout)::PlotRenderLayers as the only internal render owner.",
        ),
        (
            id = :public_attribute_owner_closed,
            status = :closed_in_tranche_5,
            fact = "On 2026-05-10, src/public_attribute_model.jl landed the exact tranche-5 snake_case attribute surface, legacy-name rejection, and the tightly local PlotKeywordSpec bridge.",
        ),
        (
            id = :public_plot_owner_closed,
            status = :closed_in_tranche_5,
            fact = "On 2026-05-10, src/public_plot_owner.jl landed Makie.@recipe PhyloPlot as the single public owner for plot(net), plot!(ax, net), phyloplot, and phyloplot!.",
        ),
        (
            id = :direct_public_surface_proof_closed,
            status = :closed_in_tranche_5,
            fact = "On 2026-05-10, direct CairoMakie-backed parity, mutation-boundary, public-limit, legacy-rejection, and dual-axis composition proof landed in test/test_public_plot_owner.jl.",
        ),
        (
            id = :docs_truth_surface_closed,
            status = :closed_in_tranche_5,
            fact = "On 2026-05-10, the docs surface switched from deferred-public-owner language to the live Makie-native public API, with a dedicated public-api page and updated verification tables.",
        ),
    ),
    stop_conditions = (
        (
            id = :single_recipe_owner_breaks_down,
            condition = "Stop if one Makie recipe owner cannot honestly drive plot(net), plot!(ax, net), phyloplot, and phyloplot! without wrapper-only semantics.",
        ),
        (
            id = :legacy_public_spellings_reappear,
            condition = "Stop if the tranche-5 public surface would need to accept legacy public spellings or preorder to stay green.",
        ),
        (
            id = :caller_owned_mutation_returns,
            condition = "Stop if plotting would need to mutate the caller-owned HybridNetwork implicitly instead of a deepcopy-owned internal copy.",
        ),
        (
            id = :compatibility_bridge_recenters,
            condition = "Stop if PlotKeywordSpec or normalize_plot_keywords would need to remain the public semantic center instead of a tightly local bridge.",
        ),
        (
            id = :proof_collapses_to_text_policing,
            condition = "Stop if the only available tranche-5 proof surface collapses to SVG, Markdown, YAML, or source-text inspection instead of live CairoMakie-backed artifacts.",
        ),
    ),
)
