const VERIFICATION_FOUNDATION = (
    target_public_surfaces = (
        (
            id = :phyloplot,
            public_name = "phyloplot",
            implemented = true,
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_visibility = :documented_convenience_surface,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "Makie.FigureAxisPlot",
        ),
        (
            id = :phyloplot_bang,
            public_name = "phyloplot!",
            implemented = true,
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_visibility = :documented_convenience_surface,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "PhyloPlot on an existing Makie axis-like owner",
        ),
        (
            id = :plot_net,
            public_name = "plot(net)",
            implemented = true,
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_visibility = :documented_primary_surface,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "Makie.FigureAxisPlot via Makie dispatch",
        ),
        (
            id = :plot_bang_axis_net,
            public_name = "plot!(ax, net)",
            implemented = true,
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_visibility = :documented_primary_surface,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "PhyloPlot on an existing Makie axis-like owner via Makie dispatch",
        ),
    ),
    lock_items = (
        (number = 2, title = "Capability parity without API mimicry"),
        (number = 5, title = "Makie composability and host-framework semantics"),
        (number = 6, title = "Honest docs and migration surface"),
        (number = 7, title = "Honest verification surface"),
    ),
    public_attribute_owner = (
        source_files = ("src/public_attribute_model.jl",),
        canonical_payload = "PhyloPlotAttributes",
        supported_public_attributes = SUPPORTED_PHYLOPLOT_ATTRIBUTES,
        recipe_attribute_surface = "Makie.attribute_names(PhyloPlot)",
        runtime_consumers = (
            "prepare_plot_layout(net, attributes; preorder=true)::PlotLayout",
            "render_plot!(target, net, attributes, layout)::PlotRenderLayers",
            "Makie.plot!(plot::PhyloPlot)",
        ),
        omitted_control_note = "The accepted public attribute surface intentionally omits separate controls for internal-node-name color, internal-node-name size, edge-length-label size, gamma-label size, and node-number size; the existing render-owner defaults remain authoritative for those groupings.",
        legacy_rejection = (
            source = "Makie.deprecated_attributes(::Type{<:PhyloPlot})",
            rejected_spellings = Tuple(migration.legacy for migration in PHYLOPLOT_ATTRIBUTE_MIGRATIONS),
        ),
        reviewer_gate = (
            clear = "the public snake_case surface is exactly the accepted attribute set, style-dependent minor-edge defaults remain source-backed, DataFrame inputs are copied on entry, legacy public spellings are rejected at the recipe boundary, and PhyloPlotAttributes is the sole accepted runtime semantic carrier.",
            reject = "it lets legacy names or preorder back onto the public surface, reintroduces a second runtime payload, or reopens omitted styling controls as ad hoc public knobs.",
        ),
    ),
    layout_annotation_owner = (
        source_files = (
            "src/layout_engine.jl",
            "src/annotation_data.jl",
        ),
        supporting_types = (
            "PlotGeometry",
            "PlotBounds",
            "PlotAnnotationData",
        ),
        canonical_payload = "PlotLayout",
        regression_suites = (
            "test/test_layout_engine.jl",
            "test/test_annotation_data.jl",
        ),
        closed_helper_regressions = (
            :edgenode_coords_with_lengths_fulltree,
            :edgenode_coords_with_lengths_majortree,
            :edgenode_coords_without_lengths_majortree,
            :level2_network_with_gamma,
            :level2_network_without_gamma,
            :mixed_missing_lengths_warning,
            :all_missing_lengths_fulltree_fallback,
            :incompatible_root,
            :preorder_mutation_boundary,
            :nodelabel_validation_and_prep,
            :edgelabel_validation_and_prep,
            :major_tree_minor_edge_midpoint,
            :helper_bounds_messages,
        ),
        render_consumer = (
            owner_tranche = 4,
            owner = "render_plot!(target, net, attributes, layout)::PlotRenderLayers",
            source_file = "src/render_adapter.jl",
            contracts = (
                "Render-time proof consumes PlotLayout geometry, bounds, and annotation tables without local geometry recomputation.",
                "Render-time proof applies only the final x_limits and y_limits carried by PhyloPlotAttributes.",
            ),
        ),
        public_surface_consumer = (
            owner_tranche = 5,
            owner = "Makie.plot!(plot::PhyloPlot)",
            source_file = "src/public_plot_owner.jl",
            contracts = (
                "The public plot owner computes PlotLayout once on a deepcopy-owned HybridNetwork and passes that payload directly to render_plot!.",
                "Public x_limits and y_limits validation reuses the helper-owned PlotBounds messages only after helper bounds are known.",
            ),
        ),
        reviewer_gate = (
            clear = "src/layout_engine.jl and src/annotation_data.jl remain the only helper owners, PlotLayout remains the canonical helper payload, render_plot! consumes that payload directly, and the Makie-native public plot owner adds no duplicate helper math.",
            reject = "it reimplements geometry, midpoint, or bounds-message semantics in the public plot owner, leaves PlotLayout implicit, or pushes helper ownership back into render-facing code.",
        ),
    ),
    render_owner = (
        source_files = ("src/render_adapter.jl",),
        supporting_types = (
            "SegmentRenderLayer",
            "ArrowTipRenderLayer",
            "TextRenderLayer",
            "PlotRenderLayers",
        ),
        typed_layer_bundle = "PlotRenderLayers",
        regression_suites = (
            "test/support/render_test_helpers.jl",
            "test/test_render_adapter.jl",
        ),
        source_set_note = ".workflow-docs/202605090307_phylomakie-makie-rebuild/04-01_tranche-04--makie-source-set.md",
        makie_source_files = (
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/recipes.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/figureplotting.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/Makie.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_plots.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_recipes/arrows.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_recipes/text.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/display.jl",
            "/home/jeetsukumaran/.julia/packages/CairoMakie/hql6v/src/screen.jl",
        ),
        primitive_entrypoints = (
            "linesegments!",
            "arrows2d!",
            "text!",
            "Makie.colorbuffer",
        ),
        public_owner_reuse = (
            owner_tranche = 5,
            owner = "Makie.plot!(plot::PhyloPlot)",
            contract = "The public recipe owner reuses render_plot! directly for both Axis and Plot targets without duplicating primitive render logic or introducing a second runtime carrier.",
        ),
        closed_render_regressions = (
            :style_distinction_fulltree_vs_majortree,
            :minor_edge_linestyle_numeric_dotted_rendering,
            :minor_edge_linestyle_blank_hides_minor_edges,
            :edgecolor_dict_fallback,
            :gamma_color_policy,
            :text_cex_scope_policy,
            :vector_text_cex_rendering,
            :tip_label_rendering,
            :internal_node_name_rendering,
            :node_number_rendering,
            :node_label_rendering,
            :edge_label_rendering,
            :edge_length_rendering,
            :edge_number_rendering,
            :explicit_limit_application,
        ),
        reviewer_gate = (
            clear = "render_plot! is the only internal render owner, PlotRenderLayers exposes the typed render proof surface, linesegments!, arrows2d!, text!, and Makie.colorbuffer remain the ratified primitive path, and the Makie-native public owner reuses the same implementation directly.",
            reject = "it adds a second render owner, reintroduces hidden current-axis state, lets public-surface proof fork the primitive path, or lets proof collapse to docs-only or source-text checks.",
        ),
    ),
    public_plot_owner = (
        source_files = ("src/public_plot_owner.jl",),
        public_recipe = "Makie.@recipe PhyloPlot (net,) begin ... end",
        makie_dispatch = (
            "Makie.plottype(::PhyloNetworks.HybridNetwork) = PhyloPlot",
            "Makie.plot!(plot::PhyloPlot)",
        ),
        supported_surfaces = (
            "plot(net)",
            "plot!(ax, net)",
            "phyloplot",
            "phyloplot!",
        ),
        stored_artifacts = (
            "resolved_attributes",
            "resolved_layout",
            "render_layers",
            "data_limits",
        ),
        direct_proof_suites = (
            "test/test_PhyloMakie.jl",
            "test/test_public_attribute_model.jl",
            "test/test_public_plot_owner.jl",
        ),
        caller_owned_network_boundary = "deepcopy(Makie.to_value(plot[:net]))",
        reviewer_gate = (
            clear = "a single Makie recipe owner drives plot(net), plot!(ax, net), phyloplot, and phyloplot!; the owner stores resolved_attributes, resolved_layout, render_layers, and data_limits on the returned plot; and caller-owned HybridNetwork inputs remain unchanged.",
            reject = "it forks surface semantics between plot and phyloplot, mutates the caller-owned network implicitly, or adds wrapper-owned render or layout logic outside the single Makie recipe owner.",
        ),
    ),
    package_truth_surfaces = (
        (
            id = :readme,
            path = "README.md",
            role = "GitHub landing surface with package synopsis, truthful installation, and quickstart guidance.",
        ),
        (
            id = :home,
            path = "docs/src/index.md",
            role = "Documenter home page that teaches the Makie-native package first.",
        ),
        (
            id = :public_api,
            path = "docs/src/public-api.md",
            role = "Live public entrypoint examples and the supported public attribute surface.",
        ),
        (
            id = :migration_guide,
            path = "docs/src/migration-guide.md",
            role = "Capability mapping and intentional-difference guidance for migrating PhyloPlots users.",
        ),
        (
            id = :verification_foundation,
            path = "docs/src/verification-foundation.md",
            role = "Source-backed verification metadata for the final package truth surface.",
        ),
        (
            id = :render_verification,
            path = "docs/src/render-verification.md",
            role = "Live CairoMakie-backed capability artifacts for style, gamma, annotation, and limit behavior.",
        ),
    ),
    accepted_design_scenarios = (
        simple_tree_no_hybrid = (
            source = "design/prod01-vision-supplement.md",
            migration_label = "Simple tree plotting with no hybrid edges",
            public_surface = "plot(net)",
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_proof_surface = "docs/src/public-api.md",
            migration_guidance = "Use `plot(net)` or `phyloplot(net)` directly for tree-only inputs. No legacy wrapper is required.",
            required_output = "Renders without error; no hybrid-edge drawing code is invoked.",
        ),
        single_reticulation_gamma = (
            source = "design/prod01-vision-supplement.md",
            migration_label = "Single reticulation with gamma display",
            public_surface = "plot(net; show_gamma = true, style = :fulltree)",
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_proof_surface = "docs/src/render-verification.md",
            migration_guidance = "Show gamma with `show_gamma = true` and choose the style on the public Makie surface rather than through a legacy plotting shell.",
            required_output = "Major and minor hybrid edges are visible in distinct colors, and the minor edge has an arrow tip.",
        ),
        style_distinction_fulltree_vs_majortree = (
            source = "design/prod01-vision-supplement.md",
            migration_label = "Style distinction between full-tree and major-tree rendering",
            public_surface = "plot!(ax, net; style = :fulltree) or plot!(ax, net; style = :majortree)",
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_proof_surface = "docs/src/render-verification.md",
            migration_guidance = "Select `style = :fulltree` for separate minor branches or `style = :majortree` for overlay-style rendering on the major tree.",
            required_output = "The full-tree style and major-tree style remain visually distinct.",
        ),
        useedgelength_scaling = (
            source = "design/prod01-vision-supplement.md",
            migration_label = "Edge-length-aware scaling",
            public_surface = "plot(net; use_edge_lengths = true)",
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_proof_surface = "docs/src/public-api.md",
            migration_guidance = "Turn on edge-length-aware x placement with `use_edge_lengths = true` on any supported public entry surface.",
            required_output = "Node x positions follow edge lengths, and missing lengths render as 1.0.",
        ),
        dataframe_label_rendering = (
            source = "design/prod01-vision-supplement.md",
            migration_label = "Node and edge annotations from data frames",
            public_surface = "plot!(ax, net; node_annotations = ..., edge_annotations = ...)",
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_proof_surface = "docs/src/public-api.md",
            migration_guidance = "Pass `node_annotations` and `edge_annotations` data frames directly on the supported public surface instead of using legacy label keywords.",
            required_output = "Node and edge labels render at the correct midpoint anchors after validation.",
        ),
        showgamma_rendering = (
            source = "design/prod01-vision-supplement.md",
            migration_label = "Gamma display on hybrid edges",
            public_surface = "plot(net; show_gamma = true)",
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_proof_surface = "docs/src/render-verification.md",
            migration_guidance = "Use `show_gamma = true` on the Makie-native public surface. Gamma text remains style-aware and color-aware.",
            required_output = "Hybrid-edge gamma text renders with the correct major and minor color semantics.",
        ),
        edgecolor_dict_fallback = (
            source = "design/prod01-vision-supplement.md",
            migration_label = "Edge-color and width control with fallback behavior",
            public_surface = "plot(net; edge_color = Dict(...), default_edge_color = ..., edge_width = ...)",
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_proof_surface = "docs/src/render-verification.md",
            migration_guidance = "Use `edge_color`, `default_edge_color`, `edge_width`, and the major/minor hybrid color controls on the supported public attribute surface.",
            required_output = "Mapped edges use the provided colors and unmapped edges fall back to the default edge color.",
        ),
        composable_dual_axes = (
            source = "design/prod01-vision-supplement.md",
            migration_label = "Dual-axis composition on existing Makie axes",
            public_surface = "plot!(ax, net) and phyloplot!(ax, net)",
            proof_owner = :test_public_plot_owner,
            proof_artifact = "test/test_public_plot_owner.jl",
            docs_proof_surface = "docs/src/public-api.md",
            migration_guidance = "Compose multiple networks by plotting into existing axes with `plot!` or `phyloplot!` instead of relying on hidden current-axis state.",
            required_output = "Two networks render into separate axes without coordinate bleed-through.",
        ),
    ),
    upstream_helper_regressions = (
        edgenode_coords_with_lengths_fulltree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        edgenode_coords_with_lengths_majortree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        edgenode_coords_without_lengths_majortree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        nodelabel_validation_and_prep = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.check_nodedataframe / prepare_nodedataframe",
        ),
        edgelabel_validation_and_prep = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.prepare_edgedataframe",
        ),
        level2_network_with_gamma = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        level2_network_without_gamma = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
    ),
    green_state_gates = (
        (
            id = :root_makie_activation,
            artifact = "The repo-local root environment loads Makie from a repo-owned dependency declaration.",
            command = "julia --project=. -e 'using Makie'",
        ),
        (
            id = :test_makie_activation,
            artifact = "The repo-local test environment loads CairoMakie and Makie for render verification.",
            command = "julia --project=test -e 'using CairoMakie; using Makie'",
        ),
        (
            id = :docs_makie_activation,
            artifact = "The repo-local docs environment loads CairoMakie and Makie for render docs.",
            command = "julia --project=docs -e 'using CairoMakie; using Makie'",
        ),
        (
            id = :package_tests,
            artifact = "Public entrypoint proof, helper and render regressions, and the final verification owner all pass together under the repo-local test project.",
            command = "julia --project=test test/runtests.jl",
        ),
        (
            id = :aqua,
            artifact = "Aqua remains supplemental proof inside the test suite and accepts the package-side Makie dependency as live.",
            command = "Aqua.test_all(PhyloMakie)",
        ),
        (
            id = :jet,
            artifact = "JET remains supplemental proof inside the test suite.",
            command = "JET.test_package(PhyloMakie; target_modules = (PhyloMakie,))",
        ),
        (
            id = :docs_build,
            artifact = "Documenter renders Home, Public API, Migration guide, Verification foundation, and Render verification from live code and source-backed metadata.",
            command = "julia --project=docs docs/make.jl",
        ),
    ),
    current_status = (
        (
            id = :public_entry_surfaces_live,
            status = :verified_on_2026_05_10,
            fact = "On 2026-05-10, plot(net), plot!(ax, net), phyloplot, and phyloplot! were all live and aligned on one Makie-native public plot owner.",
        ),
        (
            id = :runtime_carrier_live,
            status = :verified_on_2026_05_10,
            fact = "On 2026-05-10, PhyloPlotAttributes remained the sole accepted runtime semantic carrier across the public owner, layout owner, annotation owner, and render owner.",
        ),
        (
            id = :package_tests_green,
            status = :verified_on_2026_05_10,
            fact = "On 2026-05-10, julia --project=test test/runtests.jl passed 372/372 tests.",
        ),
        (
            id = :docs_build_green,
            status = :verified_on_2026_05_10,
            fact = "On 2026-05-10, julia --project=docs docs/make.jl passed with only the known Documenter example-size PNG fallback warnings on public-api.md and render-verification.md.",
        ),
        (
            id = :docs_and_migration_surface_closed,
            status = :closed_in_tranche_7,
            fact = "The package truth surface now teaches PhyloMakie as a Makie-native package first, includes a migration guide, and keeps legacy capability mapping in documentation rather than in a runtime compatibility shell.",
        ),
        (
            id = :verification_surface_closed,
            status = :closed_in_tranche_7,
            fact = "VERIFICATION_FOUNDATION now records the final package truth surface, the tranche-7 lock items, the accepted capability scenarios, and the live proof owners that keep those claims honest.",
        ),
    ),
    stop_conditions = (
        (
            id = :legacy_names_needed_for_docs_closure,
            condition = "Stop if truthful docs closure would require restoring legacy public spellings, preorder, or a runtime compatibility shell.",
        ),
        (
            id = :api_broadening_needed_for_docs_closure,
            condition = "Stop if migration or docs closure would require broadening the accepted public API beyond the settled public attribute surface.",
        ),
        (
            id = :post_tranche_6_baseline_missing,
            condition = "Stop if the repository is no longer at the post-tranche-6 runtime and public-owner state assumed by tranche 7.",
        ),
        (
            id = :proof_collapses_to_text_policing,
            condition = "Stop if capability or migration proof would need to collapse to Markdown, YAML, SVG, or source-text checks instead of live public or CairoMakie-backed artifacts.",
        ),
    ),
)
