const VERIFICATION_FOUNDATION = (
    target_public_surfaces = (
        (
            id = :phyloplot,
            public_name = "phyloplot",
            implemented = false,
            direct_proof_deferred = true,
            direct_proof_owner = 5,
            docs_visibility = :target_not_yet_implemented,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "Makie.FigureAxisPlot",
        ),
        (
            id = :phyloplot_bang,
            public_name = "phyloplot!",
            implemented = false,
            direct_proof_deferred = true,
            direct_proof_owner = 5,
            docs_visibility = :target_not_yet_implemented,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "Plot object on an existing Makie axis-like owner",
        ),
        (
            id = :plot_net,
            public_name = "plot(net)",
            implemented = false,
            direct_proof_deferred = true,
            direct_proof_owner = 5,
            docs_visibility = :target_not_yet_implemented,
            input_type = "PhyloNetworks.HybridNetwork",
            return_contract = "Makie.FigureAxisPlot via Makie dispatch",
        ),
    ),
    lock_items = (
        (number = 1, title = "Entry surfaces and return contract"),
        (number = 2, title = "Public keyword-surface parity"),
        (number = 3, title = "Layout-owner parity"),
        (number = 4, title = "Style distinction and hybrid-edge rendering"),
        (number = 5, title = "Annotation and DataFrame validation parity"),
        (number = 6, title = "Composable Makie plotting"),
        (number = 7, title = "Honest verification surface"),
    ),
    keyword_owner = (
        source_files = (
            "src/keyword_contract.jl",
            "src/keyword_normalization.jl",
        ),
        supported_plot_keywords = SUPPORTED_PLOT_KEYWORDS,
        target_public_surfaces = (
            "phyloplot",
            "phyloplot!",
            "plot(net)",
        ),
        deferred_contracts = DEFERRED_PLOT_KEYWORD_CONTRACTS,
        reviewer_gate = (
            clear = "the canonical keyword owner exists, direct keyword regressions pass, malformed explicit xlim and ylim overrides are rejected structurally at the keyword-owner boundary, helper-level annotation validation and bounds-message contracts are still closed in the layout and annotation owners, and the remaining direct public entry-surface proofs stay explicit in source, tests, and docs.",
            reject = "it reopens helper-level annotation or bounds ownership in the keyword layer, falsely marks tranche-5 direct public proof closed, or leaves the deferred direct-public boundary implicit.",
        ),
    ),
    layout_annotation_owner = (
        source_files = (
            "src/layout_engine.jl",
            "src/annotation_data.jl",
        ),
        supporting_types = (
            "PlotGeometry",
            "PlotBounds",
            "PlotAnnotationData",
        ),
        canonical_payload = "PlotLayout",
        regression_suites = (
            "test/test_layout_engine.jl",
            "test/test_annotation_data.jl",
        ),
        closed_helper_regressions = (
            :edgenode_coords_with_lengths_fulltree,
            :edgenode_coords_with_lengths_majortree,
            :edgenode_coords_without_lengths_majortree,
            :level2_network_with_gamma,
            :level2_network_without_gamma,
            :mixed_missing_lengths_warning,
            :all_missing_lengths_fulltree_fallback,
            :incompatible_root,
            :preorder_mutation_boundary,
            :nodelabel_validation_and_prep,
            :edgelabel_validation_and_prep,
            :major_tree_minor_edge_midpoint,
            :helper_bounds_messages,
        ),
        render_consumer = (
            owner_tranche = 4,
            owner = "render_plot!(ax, net, spec, layout)::PlotRenderLayers",
            source_file = "src/render_adapter.jl",
            contracts = (
                "Render-time proof consumes PlotLayout geometry, bounds, and annotation tables without local geometry recomputation.",
                "Render-time proof applies explicit xlim and ylim overrides only at the render owner boundary.",
            ),
        ),
        deferred_public_surface_proof = (
            owner_tranche = 5,
            contracts = (
                "Direct public proof for phyloplot.",
                "Direct public proof for phyloplot!.",
                "Direct Makie dispatch proof for plot(net).",
                "Direct public xlim and ylim error-path proof through the plotting entry surfaces.",
            ),
        ),
        reviewer_gate = (
            clear = "src/layout_engine.jl and src/annotation_data.jl remain the only helper owners, PlotLayout remains the canonical helper payload, render-level proof now consumes that payload directly, and direct public entry-surface proof stays deferred explicitly to tranche 5.",
            reject = "it reimplements geometry, midpoint, or helper-bounds semantics in render-facing code, leaves PlotLayout implicit, or falsely marks direct public entry-surface proof closed.",
        ),
    ),
    render_owner = (
        source_files = ("src/render_adapter.jl",),
        supporting_types = (
            "SegmentRenderLayer",
            "ArrowTipRenderLayer",
            "TextRenderLayer",
            "PlotRenderLayers",
        ),
        typed_layer_bundle = "PlotRenderLayers",
        regression_suites = (
            "test/support/render_test_helpers.jl",
            "test/test_render_adapter.jl",
        ),
        source_set_note = ".workflow-docs/202605090307_phylomakie-makie-rebuild/04-01_tranche-04--makie-source-set.md",
        makie_source_files = (
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/recipes.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/figureplotting.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/Makie.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_plots.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_recipes/arrows.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/basic_recipes/text.jl",
            "/home/jeetsukumaran/.julia/packages/Makie/p9K7f/src/display.jl",
            "/home/jeetsukumaran/.julia/packages/CairoMakie/hql6v/src/screen.jl",
        ),
        primitive_entrypoints = (
            "linesegments!",
            "arrows2d!",
            "text!",
            "Makie.colorbuffer",
        ),
        closed_render_regressions = (
            :style_distinction_fulltree_vs_majortree,
            :edgecolor_dict_fallback,
            :gamma_color_policy,
            :tip_label_rendering,
            :internal_node_name_rendering,
            :node_number_rendering,
            :node_label_rendering,
            :edge_label_rendering,
            :edge_length_rendering,
            :edge_number_rendering,
            :explicit_limit_application,
        ),
        reviewer_gate = (
            clear = "render_plot! is the only internal render owner, PlotRenderLayers exposes the direct owner proof surface, linesegments!, arrows2d!, text!, and Makie.colorbuffer are recorded as the ratified primitive path, and all tranche-5 public surfaces remain absent and explicitly deferred.",
            reject = "it adds a public plotting surface, reintroduces hidden current-axis state, lets gamma text inherit dict-driven edge colors, or lets render proof collapse to docs-only or source-text checks.",
        ),
    ),
    accepted_design_scenarios = (
        simple_tree_no_hybrid = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Renders without error; no hybrid-edge drawing code is invoked.",
        ),
        single_reticulation_gamma = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Major and minor hybrid edges are visible in distinct colors, and the minor edge has an arrow tip.",
        ),
        style_distinction_fulltree_vs_majortree = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "The full-tree style and major-tree style remain visually distinct.",
        ),
        useedgelength_scaling = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Node x positions follow edge lengths, and missing lengths render as 1.0.",
        ),
        dataframe_label_rendering = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Node and edge labels render at the correct midpoint anchors after validation.",
        ),
        showgamma_rendering = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Hybrid-edge gamma text renders with the correct major and minor color semantics.",
        ),
        edgecolor_dict_fallback = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 4,
            closure_status = :closed_render_owner,
            required_output = "Mapped edges use the provided colors and unmapped edges fall back to the default edge color.",
        ),
        composable_dual_axes = (
            source = "design/prod01-vision-supplement.md",
            direct_proof_owner = 5,
            closure_status = :deferred_public_surface_proof,
            required_output = "Two networks render into separate axes without coordinate bleed-through.",
        ),
    ),
    upstream_helper_regressions = (
        edgenode_coords_with_lengths_fulltree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        edgenode_coords_with_lengths_majortree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        edgenode_coords_without_lengths_majortree = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        nodelabel_validation_and_prep = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.check_nodedataframe / prepare_nodedataframe",
        ),
        edgelabel_validation_and_prep = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.prepare_edgedataframe",
        ),
        level2_network_with_gamma = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
        level2_network_without_gamma = (
            source = "PhyloPlots.jl/test/test_phylonetworkPlots.jl",
            proof_owner = 3,
            helper_owner = "PhyloPlots.edgenode_coordinates",
        ),
    ),
    green_state_gates = (
        (
            id = :root_makie_activation,
            artifact = "The repo-local root environment loads Makie from a repo-owned dependency declaration.",
            command = "julia --project=. -e 'using Makie'",
        ),
        (
            id = :test_makie_activation,
            artifact = "The repo-local test environment loads CairoMakie and Makie for render verification.",
            command = "julia --project=test -e 'using CairoMakie; using Makie'",
        ),
        (
            id = :docs_makie_activation,
            artifact = "The repo-local docs environment loads CairoMakie and Makie for render docs.",
            command = "julia --project=docs -e 'using CairoMakie; using Makie'",
        ),
        (
            id = :package_tests,
            artifact = "Shell-owner, keyword-owner, layout-owner, annotation-owner, render-owner, and verification-owner tests pass together under the repo-local test project.",
            command = "julia --project=test test/runtests.jl",
        ),
        (
            id = :aqua,
            artifact = "Aqua remains supplemental proof inside the test suite and now accepts the package-side Makie dependency as live.",
            command = "Aqua.test_all(PhyloMakie)",
        ),
        (
            id = :jet,
            artifact = "JET remains supplemental proof inside the test suite.",
            command = "JET.test_package(PhyloMakie; target_modules = (PhyloMakie,))",
        ),
        (
            id = :docs_build,
            artifact = "Documenter renders the source-backed verification-foundation page and the render-verification page from live CairoMakie code.",
            command = "julia --project=docs docs/make.jl",
        ),
    ),
    current_status = (
        (
            id = :dependency_activation_closed,
            status = :closed_in_tranche_4,
            fact = "On 2026-05-10, the root, test, and docs projects all resolved and loaded the Makie-family dependencies through repo-owned environments.",
        ),
        (
            id = :render_owner_closed,
            status = :closed_in_tranche_4,
            fact = "On 2026-05-10, src/render_adapter.jl landed render_plot!(ax, net, spec, layout)::PlotRenderLayers as the only internal render owner, and the package shell acknowledged Makie without exposing public plotting entry surfaces.",
        ),
        (
            id = :render_verification_closed,
            status = :closed_in_tranche_4,
            fact = "On 2026-05-10, CairoMakie-backed render regressions and render-verification docs closed the tranche-4 style, color, width, text-anchor, and explicit-limit proof surface.",
        ),
        (
            id = :target_surfaces_still_deferred,
            status = :intentional_current_state,
            fact = "The plotting entry surfaces remain intentionally unimplemented after tranche 4; phyloplot, phyloplot!, PhyloPlot, Makie.plottype(::HybridNetwork), and plot(net) public proof remain deferred to tranche 5.",
        ),
    ),
    stop_conditions = (
        (
            id = :would_require_public_entry_surface,
            condition = "Stop if tranche-4 work would require implementing phyloplot, phyloplot!, PhyloPlot, Makie.plottype(::HybridNetwork), or plot(net) dispatch.",
        ),
        (
            id = :helper_owner_regression,
            condition = "Stop if layout_engine or annotation_data semantics would need to move back out of PlotLayout and into render code.",
        ),
        (
            id = :source_set_drift_from_ratified_note,
            condition = "Stop if the resolved Makie dependency tree or primitive-source files drift materially from the ratified source-set note before tranche 5 updates it.",
        ),
        (
            id = :docs_truth_boundary_violation,
            condition = "Stop if docs would need to claim direct public entry-surface closure to stay green.",
        ),
        (
            id = :render_proof_degenerates_to_text_policing,
            condition = "Stop if the only available proof surface collapses to SVG, Markdown, YAML, or source-text inspection instead of live CairoMakie-backed artifacts.",
        ),
    ),
)
